Migration to ORx-style init scripts
To keep the platform easy(er) to maintain, we've unified all system
initalization between Lighthouse and ORx. This means that most init scripts are
now proper BusyBox init scirpts and also:

- netowrking is managed using ifupdown
- hostapd is using a file rather than config generated by init script
- dropbear stores configuration in /etc/dropbear symlinked to
  /mnt/persist/sysconfig/dropbear

Release containing these changes should implement some kind of one-time
migration of old configs.

Signed-off-by: Branko Vukelic <branko@outernet.is>

diff --git a/rootfs/rootfs_overlay/etc/init.d/S50dropbear b/rootfs/rootfs_overlay/etc/init.d/S50dropbear
--- a/rootfs/rootfs_overlay/etc/init.d/S50dropbear
+++ b/rootfs/rootfs_overlay/etc/init.d/S50dropbear
@@ -3,58 +3,64 @@
 # Starts dropbear sshd.
 #
 
-RSA_KEY=/mnt/persist/dropbear.rsa
-DSS_KEY=/mnt/persist/dropbear.dss
-PID_FILE=/var/run/dropbear.pid
+KEYDIR=/etc/dropbear
+KEYDSS=$KEYDIR/dss_host_key
+KEYRSA=$KEYDIR/rsa_host_key
+DROPBEAR_PID=/var/run/dropbear.pid
+DAEMON=/usr/sbin/dropbear
 
-# Make sure the dropbearkey progam exists
 [ -f /usr/bin/dropbearkey ] || exit 0
 
+keygen() {
+    mkdir -p $KEYDIR
+    chmod 700 $KEYDIR
+    if [ ! -f $KEYDSS ]
+    then
+        echo -n "Generating DSS host key..."
+        dropbearkey -t dss -f $KEYDSS > /dev/null 2>&1
+        echo OK
+    fi
+    if [ ! -f $KEYRSA ]
+    then
+        echo -n "Generating RSA host key..."
+        dropbearkey -t rsa -f $KEYRSA > /dev/null 2>&1
+        echo OK
+    fi
+}
+
 start() {
-  # Check for the Dropbear RSA key
-  if [ ! -f $RSA_KEY ] ; then
-    echo -n "SSH: Generating rsa key... "
-    /usr/bin/dropbearkey -t rsa -f $RSA_KEY > /dev/null 2>&1
-  fi
-
-  # Check for the Dropbear DSS key
-  if [ ! -f $DSS_KEY ] ; then
-    echo -n "SSH: Generating dsa key... "
-    /usr/bin/dropbearkey -t dss -f $DSS_KEY > /dev/null 2>&1
-  fi
-
-  # Start ssh
-  echo -n "Starting dropbear sshd: "
-  start-stop-daemon -S -q -p $PID_FILE --exec /usr/sbin/dropbear -- -d $DSS_KEY -r $RSA_KEY
-  [ $? -eq 0 ] && echo "OK" || echo "failed"
+    keygen
+	echo -n "Starting dropbear sshd: "
+	umask 077
+	start-stop-daemon -S -q -p $DROPBEAR_PID -x $DAEMON \
+        -- -w -d $KEYDSS -r $KEYRSA
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 
 stop() {
-  if [ -f $PID_FILE ]; then
-    echo -n "Stopping dropbear sshd: "
-    start-stop-daemon -K -q -o -p $PID_FILE
-    [ $? -eq 0 ] && echo "OK" || echo "failed"
-  fi
+	echo -n "Stopping dropbear sshd: "
+	start-stop-daemon -K -q -p $DROPBEAR_PID -x $DAEMON
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 
 restart() {
-  stop
-  start
+	stop
+	start
 }
 
 case "$1" in
   start)
-    start
-    ;;
+  	start
+	;;
   stop)
-    stop
-    ;;
+  	stop
+	;;
   restart|reload)
-    restart
-    ;;
+  	restart
+	;;
   *)
-    echo $"Usage: $0 {start|stop|restart}"
-    exit 1
+	echo "Usage: $0 {start|stop|restart}"
+	exit 1
 esac
 
 exit $?
