Ensure dropbear can start
Between 2.x and 3.x, a regression was introduced that cause outerbox to not
allow host key creation. This patch fixes the issue by ensuring an empty
/etc/dropbear directory is present in the rootfs beore boot. This patch also
updates the dropbear init script to the simplified version used in rxOS.

Signed-off-by: Branko Vukelic <branko@outernet.is>

diff --git a/rootfs/rootfs_overlay/etc/init.d/S50dropbear b/rootfs/rootfs_overlay/etc/init.d/S50dropbear
--- a/rootfs/rootfs_overlay/etc/init.d/S50dropbear
+++ b/rootfs/rootfs_overlay/etc/init.d/S50dropbear
@@ -2,65 +2,50 @@
 #
 # Starts dropbear sshd.
 #
-
-KEYDIR=/etc/dropbear
-KEYDSS=$KEYDIR/dss_host_key
-KEYRSA=$KEYDIR/rsa_host_key
-DROPBEAR_PID=/var/run/dropbear.pid
-DAEMON=/usr/sbin/dropbear
-
-[ -f /usr/bin/dropbearkey ] || exit 0
-
-keygen() {
-    mkdir -p $KEYDIR
-    chmod 700 $KEYDIR
-    if [ ! -f $KEYDSS ]
-    then
-        echo -n "Generating DSS host key..."
-        dropbearkey -t dss -f $KEYDSS > /dev/null 2>&1
-        echo OK
-    fi
-    if [ ! -f $KEYRSA ]
-    then
-        echo -n "Generating RSA host key..."
-        dropbearkey -t rsa -f $KEYRSA > /dev/null 2>&1
-        echo OK
-    fi
-}
+# This file is part of outerbox.
+# outerbox is free software licensed under the
+# GNU GPL version 3 or any later version.
+#
+# This file is a modified version of the init script found in the Buildroot
+# source tree.  The copyright information for the file is not available, so we
+# use the year of the original Buildroot release. The file is probably older, 
+# though.
+#
+# The modified version removes symlink handling code which is not needed in
+# rxOS.
+#
+# (c) 2006-2016 Buildroot developers
+# (c) 2016 Outernet Inc
+# Some rights reserved.
 
 start() {
-    keygen
-	echo -n "Starting dropbear sshd: "
-	umask 077
-	start-stop-daemon -S -q -p $DROPBEAR_PID -x $DAEMON \
-        -- -w -d $KEYDSS -r $KEYRSA
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
+  printf "Starting SSH: "
+  umask 077
+  start-stop-daemon -S -q -p /var/run/dropbear.pid \
+    --exec /usr/sbin/dropbear -- -wR
+  [ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 
 stop() {
-	echo -n "Stopping dropbear sshd: "
-	start-stop-daemon -K -q -p $DROPBEAR_PID -x $DAEMON
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
-}
-
-restart() {
-	stop
-	start
+  printf "Stopping SSH: "
+  start-stop-daemon -K -q -p /var/run/dropbear.pid
+  [ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 
 case "$1" in
   start)
-  	start
-	;;
+    start
+    ;;
   stop)
-  	stop
-	;;
+    stop
+    ;;
   restart|reload)
-  	restart
-	;;
+    stop
+    start
+    ;;
   *)
-	echo "Usage: $0 {start|stop|restart}"
-	exit 1
+    echo "Usage: $0 {start|stop|restart}"
+    exit 1
 esac
 
 exit $?
